language: python
env:
 - DJANGO_VERSION=1.8
 - DJANGO_VERSION=1.9
 - DJANGO_VERSION=1.11
python:
 - "2.7"
 - "3.5"
 - "pypy"
 - "pypy3"
install:
 - pip install -r requirements.txt
 - pip install -q Django==$DJANGO_VERSION
 - python setup.py -q install
script: py.test
